### ISSUE TITLE
Unable to get device configuration file

### ISSUE THREAD

**Issue by lonkhuijzen** [tomeko12/pyelectroluxconnect#18]
Since i think the change to 3.16 i've got this issue. It used to work with 3.15 (home assistent integration)

It can connect and auth with the api because i do get my own PNC, ELC and SN returned. 1st line in the errormsg is edited for security reasons! 

I tested it with the following code on the latest version:

```
import pyelectroluxconnect
ses = pyelectroluxconnect.Session("XXX@XXX.XX", "XXX", region="emea", tokenFileName = ".electrolux-token", country = "NL", language = None, deviceId = "CustomDeviceId", verifySsl = True)
ses.login()
```

And the errormsg

```
Exception in _getApplianceConfiguration(PNC, ELC and SN edited for security reasons): Unable to get device configuration file.
Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 277, in _getApplianceConfiguration
    raise Exception("Unable to get device configuration file.")
Exception: Unable to get device configuration file.
Exception in _getAppliancesList: Unable to get device configuration file.
Traceback (most recent call last):
  File "/home/orangepi/.local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 202, in _getAppliancesList
    applianceProfile = self._getApplianceConfiguration(self._applianceIndex[device["appliance_id"]]["pnc"],
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orangepi/.local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 280, in _getApplianceConfiguration
    raise Error(err) from None
pyelectroluxconnect.Session.Error: Unable to get device configuration file.
Error while get Appliances list: Unable to get device configuration file.
Unable to get device configuration file.
Traceback (most recent call last):
  File "/home/orangepi/test.py", line 3, in <module>
    ses.login()
  File "/home/orangepi/.local/lib/python3.11/site-packages/pyelectroluxconnect/Session.py", line 1073, in login
    raise Exception(ErrorArg) from None
Exception: Unable to get device configuration file.
```

**Comment by Dejmal69** [comment]
Hi,
i have the same problem.
Thanks

**Comment by tomeko12** [comment]
Hi.
@lonkhuijzen , @Dejmal69, what are appliances PNC and ELC numbers?

**Comment by lonkhuijzen** [comment]
Hi tomeko12,Thx for the response!PNC: 914501102ELC: 00Thx!ChristianOp 28 okt 2023 om 10:56 heeft tomeko12 ***@***.***> het volgende geschreven:﻿
Hi.
@lonkhuijzen , @Dejmal69, what are appliances PNC and ELC numbers?

**Comment by Dejmal69** [comment]
Hi tomeko12 my PNC: 91450102100. But where look at ELC?

**Comment by tomeko12** [comment]
Please update pyelectroluxconnect to 0.3.20 and try.

**Comment by lonkhuijzen** [comment]
Some progress:) but a new error:

`Configuration file /home/orangepi/.pyelectroluxconnect/914501102_00_00.zip has wrong MD5 checksum`

**Comment by lonkhuijzen** [comment]
Above error is probably not an issue. The Electrolux Care Integration in HomeAssistant which uses this package implemented this update and it got fixed.

thx for the work!
