### ISSUE TITLE
No longer able to login

### ISSUE THREAD

**Issue by miguelangel-nubla** [tomeko12/pyelectroluxconnect#9]
Started receiving "Unauthorized (401)" out of the blue. Double checked and the credentials work on AEG Care app.

Using this to test:
```
import os
import pprint
import pyelectroluxconnect
ses = pyelectroluxconnect.Session("XXXXXXX@gmail.com", "XXXXXXXX", region="EMEA")
ses.login()
appllist = ses.getAppliances()
d = open(f"devices.json", "w")
d.write(str(appllist))
d.close()
for appliance in appllist:
    # print(ses.getApplianceConnectionState(appliance))
    p = open(f"{appllist[appliance]['alias']}-profil.json", "w")
    p.write(str(ses.getApplianceProfile(appliance)))
    p.close()
    s = open(f"{appllist[appliance]['alias']}-state.json", "w")
    s.write(str(ses.getApplianceState(appliance, rawOutput=False)))
    s.close()
    rs = open(f"{appllist[appliance]['alias']}-rawstate.json", "w")
    rs.write(str(ses.getApplianceState(appliance, rawOutput=True)))
    rs.close()
```
output:
```
Exception in _getAppliancesList: Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 186, in _getAppliancesList
    _json = self._requestApi(urls.getAppliances(self._username))
  File "/home/user/.local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 978, in _requestApi
    raise ResponseError(errcode, message) from None
pyelectroluxconnect.Session.ResponseError: Invalid API response: Unauthorized (401)
Error while get Appliances list: Invalid API response: Unauthorized (401)
Invalid API response: Unauthorized (401)
Traceback (most recent call last):
  File "/mnt/t/electrolux/test.py", line 5, in <module>
    ses.login()
  File "/home/user/.local/lib/python3.10/site-packages/pyelectroluxconnect/Session.py", line 1071, in login
    raise Exception(ErrorArg) from None
Exception: Invalid API response: Unauthorized (401)
```

**Comment by tomeko12** [comment]
Fixed in 0.3.15
